### ISSUE TITLE
wget crash

### ISSUE THREAD

**Issue by 0xD34DC0DE** [LuxCoreRender/WindowsCompile#7]
the wget executable keeps crashing when handling large files and is likely due to lfh
(low fragmentation heap)
Wget is corrupting its heap

Edit: By modifying the getdeps.bat and adding the -q option to the function download file "quiet" the problem seems to not be hapenning

**Comment by Dade916** [comment]
Are you aware that you don't need to build dependecies ? It is a very long and tedious process, they are already available in binary format at https://github.com/LuxCoreRender/WindowsCompileDeps

**Comment by Dade916** [comment]
Ok but the -q option is now working for you ?

**Comment by acasta69** [comment]
This issue is very old, the opener did not complain any more and I was never able to reproduce it.
I think it can be closed.
