### ISSUE TITLE
"atlbase.h": No such file or directory

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/WindowsCompile#8]
When I try to compile on Windows with VS2017, I get this error in the luxcoreui stage:
```
f:\users\simon_2\projekte\luxcore_compile2\luxcore\samples\luxcoreui\deps\nfd\nfd_win.cpp(16): 
fatal error C1083: can't open file (include): "atlbase.h": No such file or directory
```
Can you reproduce this?

**Comment by acasta69** [comment]
I've seen this only today...
Never had that problem: is it now solved or still there?
It seems that "Visual C++ ATL support" is needed to build luxcoreui.
It can be selected in the visual studio installer as an individual component:
https://i.stack.imgur.com/NmM64.png

**Comment by Theverat** [comment]
>It seems that "Visual C++ ATL support" is needed to build luxcoreui.
>It can be selected in the visual studio installer as an individual component:

Thanks, this fixed the problem.
